### ISSUE TITLE
configSchema.json out of date

### ISSUE THREAD

**Issue by philipgloyne** [davidesner/keboola-bingads-ex#3]
Great project, thanks. 

I believe your configSchema.json might be out-of-date. The readme.md has some use-case config.json files but the seem to be missing some fields like 'oauth_api'. Do you mind sharing a example config that you use (with the private fields hidden of course)?

**Comment by davidesner** [comment]
Hi Philip,

thank you:) It is a bit outdated, especially the documentation that is
true, sorry for that. I am expecting to migrate to new API v.11 in upcoming
months anyway since BingAds is deprecating the version I used in the
project.

The app is design as a custom component to use in a Keboola Connection
platform. The oauth credentials are injected from its oAuth bundle. I am
enclosing the sample configuration as it is expected from the KBC
interface. Place your oAuth tokens instead of the place
holders REFRESH_TOKEN, etc.

Hope this helps.

David
